server:
  port: 80
  servlet:
    context-path: /

spring:
  data:
    elasticsearch:
      cluster-name: my-elasticsreach-application #默认即为 elasticsearch
      cluster-nodes: 192.168.1.233:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      repositories:
        enabled: true
      properties:
       # path: /data/project/target/elastic
        transport:
          tcp:
            connect_timeout: 120s


logging:
  level:
    root: info

#中文教程地址 https://es.xiaoleilu.com/010_Intro/25_Tutorial_Indexing.html
#英文官网：https://www.elastic.co/guide/en/elasticsearch/reference/5.2/docs-index_.html